export const fieldTypes: Record<string, Record<string, "string" | "number" | "boolean" | "date">> = {
  user: {
    id: "number",
    firstname: "string",
    lastname: "string",
    email: "string",
    password: "string",
    role: "string",
    isActive: "boolean",
    createdAt: "date",
    updatedAt: "date",
  },
  category: {
    id: "number",
    name: "string",
    createdAt: "date",
    updatedAt: "date",
  },
  brand: {
    id: "number",
    name: "string",
    createdAt: "date",
    updatedAt: "date",
  },
  fuelType: {
    id: "number",
    name: "string",
    createdAt: "date",
    updatedAt: "date",
  },
  car: {
    id: "number",
    title: "string",
    description: "string",
    price: "number",
    year: "number",
    mileage: "number",
    brandId: "number",
    categoryId: "number",
    fuelTypeId: "number",
    createdAt: "date",
    updatedAt: "date",
  },
};
